#!/bin/ksh
#----------------------------------------------------------------------
#
#     SCRIPT: run_erai_kk
#
#     LANGUAGE: ksh
#
#     DESCRIPTION:
#
# 
#     A script to find highs or lows in the 6 hourly ERAI mslp 
#     This (new) version calls the UM version of the tracking scheme
#
#     WRITTEN: A Pepler (based on code by K Braganza).
#

#----------------------------------------------------------------------
#     delete function for temporary files

function check_delete {
    if [[ -f $1 ]]; then
	rm -f $1
    fi
}
#----------------------------------------------------------------------
bpath=/home/z3478332/UM/cts.dir

CYCBIN=$bpath/software.dir/cyc.dir/cycbin
cyclocx=$CYCBIN/cycloc3x.hr
trackx=$CYCBIN/trackx.hr
trackmnx=$CYCBIN/trackmnx.hr
tstatx=$CYCBIN/tstatx.hr

spath=$bpath/mine/code
opath=/srv/ccrc/data34/z3478332/CMIP-WRF-ECLs/outputUM
diagnostic=$opath/diagnostics.out

#----------------------------------------------------------------------

type=low

print "\nSCRIPT: runplot_mslp_day VERSION: 1.0"
print "\nSCRIPT: runplot_mslp_day VERSION: 1.0" > $diagnostic

#----------------------------------------------------------------------

echo "Beginning MAIN" >> $diagnostic

firstyear=1990
lastyear=2009
proj=100
DFF=2.0
NN=$((proj*2+1))

set -A models zero miroc echam5 cccma csiromk3
for cmip in  2 3; do

mm=${models[$cmip]}
outpath=$opath/proj100/outputUM_${mm}_50_rad2cv06

if [[ $cmip -eq 2 ]] ; then
  gmake=$spath/gausmake_echam5
  gfile=6hourecham.ingausmake.kk
elif [[ $cmip -eq 3 ]] ; then
  gmake=$spath/gausmake_cccma
  gfile=6hourcccma.ingausmake.kk
else
  print "Only working for echam5 and cccma atm"
  break
fi

print $outpath
print "Running for" $firstyear to $lastyear

#----------------------------------------------------------------------
# loop through the years

iyear=$firstyear
while [[ $iyear -le $lastyear ]]; do   
#for iyear in  2006 ; do


#----------------------------------------------------------------------
# loop through the seasons

dname="ann"

echo $iyear $dname >> $diagnostic

date1_loc=$(($iyear-1))1201
date2_loc=$(($iyear))1231

echo 'date1 loc = ' $date1_loc >> $diagnostic 
echo 'date2 loc = ' $date2_loc >> $diagnostic 

if [[ $iyear -eq 1999 || $iyear -eq 2000 || $iyear -eq 1900 || $iyear -eq 2099 || $iyear -eq 2100 ]] ; then
    date1a=$(($iyear-81))1201
    date2a=$(($iyear-80))1231
    date1_loc2=${date1a:2:6}
    date2_loc2=${date2a:2:6}
else
    date1_loc2=${date1_loc:2:6}
    date2_loc2=${date2_loc:2:6}
fi

print $date1_loc $date1_loc2
print $date2_loc $date2_loc2

#----------------------------------------------------------------------
# set up output directories

   if [[ -a $outpath && -d $outpath ]] ; then
    outpath=$outpath
   else
    mkdir $outpath  2>> stderr
    outpath=$outpath
   fi

#----------------------------------------------------------------------
# loop through the months in the season
# Deleted all the cat part of this file
# as done during gausmake instead

check_delete ingausmake
check_delete incycloc
check_delete intrack
check_delete loc_output
check_delete tape1
check_delete tape11
check_delete stdout
#----------------------------------------------------------------------
# set up output directories

print 'Output directories setted up.'
print 'Proceeding to running script out.'

#----------------------------------------------------------------------
#     Simple processing script

function runjob {
#if [[ -s $infile ]]; then
# print "/PROCESSING FOR $type/s FOR INPUT FILE: $infile"  >> $diagnostic
#else
# print "INPUT FILE DOES NOT EXSIST!: $infile"  >> $diagnostic
# return
#fi

print "AUTOMATICALLY EDITING CONTROL FILES" >> $diagnostic
# Added gausmake which makes the files
sed -e "s/YYYYMMDD1/$date1_loc/" -e "s/YYYYMMDD2/$date2_loc/" -e "s/XLON/$lons/" -e "s/YLAT/$lats/" -e "s/GGGG/$grid/" -e "s/CCCC/$cmip/" -e "s/VVVV/$wrfv/" $gfile > ingausmake
sed -e "s/YYMMDD1/$date1_loc2/" -e "s/YYMMDD2/$date2_loc2/" -e "s/NN/$NN/g" -e "s/DFF/$DFF/g" -e "s/PROJ/$proj/" 6hourcmip.incycloc.kk > incycloc
sed -e "s/YYMMDD1/$date1_loc2/g" -e "s/YYMMDD2/$date2_loc2/" 6hourerai.intrack.kk > intrack

check_delete tape1
check_delete tape11

print 'calling gausmake'

if [[ $iyear -eq 1999 || $iyear -eq 2000  || $iyear -eq 1900 || $iyear -eq 2099 || $iyear -eq 2100 ]] ; then
    $gmake spec
else
    $gmake norm
fi
cp tape11 monthfile

print 'calling cycloc'
#$CYCBIN/cycloc3x.hr -i incycloc -d 1 -c loc_output -z $topo monthfile >> stdout
$CYCBIN/cycloc3x.hr -i incycloc -c loc_output monthfile #>> stdout
#cp loc_output $outpath/mslpo.$date1_loc$date2_loc.00001800.gcycloc

print 'calling track'
$CYCBIN/trackx.hr  -FO -i intrack -d 1 -c loc_output >> stdout
touch trackfile
cat thist?.1 > trackfile
rm -f thist*
#cp trackfile $outpath/mslpo.$date1_loc$date2_loc.00001800.trackfile

ofile=$outpath/tracks_${iyear}.dat
print 'calling awk'
touch $ofile
awk -f $spath/maketracks_UM.awk trackfile > $ofile

#check_delete tape11
#check_delete trackfile
#check_delete monthfile

}

echo "Run Job" >> $diagnostic
runjob
iyear=$(($iyear+1))
print iyear
rm stdout
#----------------------------------------------------------------------
done  # year loop
done #model loop

#----------------------------------------------------------------------
echo "Finished Main" >> $diagnostic

exit
