#!/bin/ksh
#----------------------------------------------------------------------
#
#     SCRIPT: run_erai_kk
#
#     LANGUAGE: ksh
#
#     DESCRIPTION:
#
# 
#     A script to find highs or lows in the 6 hourly ERAI mslp 
#     This (new) version calls the UM version of the tracking scheme
#
#     WRITTEN: A Pepler (based on code by K Braganza).
#

#----------------------------------------------------------------------
#     delete function for temporary files

function check_delete {
    if [[ -f $1 ]]; then
	rm -f $1
    fi
}
#----------------------------------------------------------------------
bpath=/home/z3478332/UM/cts.dir

CYCBIN=$bpath/software.dir/cyc.dir/cycbin
cyclocx=$CYCBIN/cycloc3x.hr
trackx=$CYCBIN/trackx.hr
trackmnx=$CYCBIN/trackmnx.hr
tstatx=$CYCBIN/tstatx.hr

spath=$bpath/mine/code
opath=$bpath/mine/cyc_out
stdout=$opath/stdout.out
stderr=$opath/stderr.out
diagnostic=$opath/diagnostics.out

check_delete $stdout
touch $stdout
check_delete $stderr
touch $stderr
check_delete $diagnostic
touch $diagnostic

#----------------------------------------------------------------------

type=low

print "\nSCRIPT: runplot_mslp_day VERSION: 1.0"
print "\nSCRIPT: runplot_mslp_day VERSION: 1.0" > $diagnostic

#----------------------------------------------------------------------

echo "Beginning MAIN" >> $diagnostic

firstyear=1980
lastyear=1999

print "Running for" $firstyear to $lastyear

#----------------------------------------------------------------------
# loop through the years

iyear=$firstyear

while [[ $iyear -le $lastyear ]]; do   


#----------------------------------------------------------------------
# loop through the seasons

dname="ann"

echo $iyear $dname >> $diagnostic
date1_loc=$(($iyear-1))1201
date2_loc=$(($iyear+1))0101

echo 'date1 loc = ' $date1_loc >> $diagnostic 
echo 'date2 loc = ' $date2_loc >> $diagnostic 
date1_loc2=${date1_loc:2:6}
#typeset -Z6 date1_loc2
date2_loc2=${date2_loc:2:6}
#typeset -Z6 date2_loc2

print $date1_loc $date1_loc2


#----------------------------------------------------------------------
# loop through the months in the season
# Deleted all the cat part of this file
# as done during gausmake instead

check_delete ingausmake
check_delete incycloc
check_delete intrack
check_delete loc_output
check_delete tape1
check_delete tape11
#----------------------------------------------------------------------
# set up output directories

outpath=$opath/$dname.dir

   if [[ -a $outpath && -d $outpath ]] ; then
    outpath=$outpath
   else
    mkdir $outpath  2>> $stderr
    outpath=$outpath
   fi

print 'Output directories setted up.'
print 'Proceeding to running script out.'

#----------------------------------------------------------------------
#     Simple processing script

function runjob {
#if [[ -s $infile ]]; then
# print "/PROCESSING FOR $type/s FOR INPUT FILE: $infile"  >> $diagnostic
#else
# print "INPUT FILE DOES NOT EXSIST!: $infile"  >> $diagnostic
# return
#fi

print "AUTOMATICALLY EDITING CONTROL FILES" >> $diagnostic
# Added gausmake which makes the files
sed -e "s/YYYYMMDD1/$date1_loc/" -e "s/YYYYMMDD2/$date2_loc/" 6hourerai.ingausmake.kk > ingausmake
sed -e "s/YYMMDD1/$date1_loc2/" -e "s/YYMMDD2/$date2_loc2/" 6hourerai.incycloc.kk > incycloc
sed -e "s/YYMMDD1/$date1_loc2/" -e "s/YYMMDD2/$date2_loc2/" 6hourerai.intrack.kk > intrack

check_delete tape1
check_delete tape11

print 'calling gausmake'
$spath/gausmake_erai
cp tape11 monthfile

print 'calling cycloc'
#cyclocx -i incycloc -c loc_output -z $bpath/test_mslp.dir/data.dir/zs.era40.cmp monthfile 1>> $stdout 2>> $stderr
$CYCBIN/cycloc3x.hr -i incycloc -d 1 -c loc_output monthfile >> $stdout
cp loc_output $outpath/mslpo.$date1_loc$date2_loc.00001800.gcycloc

print 'calling track'
$CYCBIN/trackx.hr  -FO -i intrack -c loc_output >> $stdout
touch trackfile
cat thist?.1 > trackfile
rm -f thist*
cp trackfile $outpath/mslpo.$date1_loc$date2_loc.00001800.trackfile

ofile=$outpath/tracks_${iyear}.dat
print 'calling awk'
touch $ofile
awk -f $spath/maketracks_UM.awk trackfile > $ofile

check_delete tape11
check_delete trackfile
check_delete monthfile

}

echo "Run Job" >> $diagnostic
runjob
iyear=$(($iyear+1))
print iyear
#----------------------------------------------------------------------
done  # year loop

#----------------------------------------------------------------------
echo "Finished Main" >> $diagnostic

exit
